experiment_name:
seed: 0

environment: minigrid
    
minigrid:
    size: [20, 20]
    living_reward: 0
    no_op_penalty: 0
    starting_position:  [0, 0] # random if not given
    reward_position:  [18, 12] # random if not given
    episode_timeout:  100 # infinity if not given

learner: q_learner

q_learner:
    alpha: 0.1
    gamma: 0.9
    policy: epsilon_greedy
    epsilon_greedy:
        epsilon: 0.1

training:
    num_episodes: 100