environment: minigrid
    
minigrid:
    size: [10, 10]
    living_reward: 0
    no_op_penalty: 0
    starting_position:  # random if not given
    reward_position:  # random if not given

learner: q_learner

q_learner:
    alpha: 0.1
    gamma: 0.9
    policy: epsilon_greedy
    epsilon_greedy:
        epsilon: 0.1

training:
    num_episodes: 100