experiment_name:
seed: 0

environment: minigrid
    
minigrid:
    size: [20, 20]
    living_reward: 0
    no_op_penalty: 0
    starting_position:  [0, 0] # random if not given
    reward_position:  [18, 12] # random if not given
    episode_timeout:  200 # infinity if not given

learner: 
    type: sarsa_lambda
    learning_rate: 0.1
    discount_factor: 0.9    
    epsilon: 0.1
    visitation_penalty: 0
    initialisation: random

sarsa_lambda:
    trace_lambda: 0.1

training:
    num_episodes: 500