class Constants:

    EPSILON_GREEDY = "epsilon_greedy"

    # config
    SIZE = "size"
    LIVING_REWARD = "living_reward"
    NO_OP_PENALTY = "no_op_penalty"
    STARTING_POSITION = "starting_position"
    REWARD_POSITION = "reward_position"
    ENVIRONMENT = "environment"
    MINIGRID = "minigrid"
    EPISODE_TIMEOUT = "episode_timeout"
    EPSILON = "epsilon"
    POLICY = "policy"
    EPSILON_GREEDY = "epsilon_greedy"
    Q_LEARNER = "q_learner"
    SARSA_LAMBDA = "sarsa_lambda"
    TRACE_LAMBDA = "trace_lambda"
    LEARNING_RATE = "learning_rate"
    DISCOUNT_FACTOR = "discount_factor"
    LEARNER = "learner"
    TRAINING = "training"
    NUM_EPISODES = "num_episodes"
    EXPERIMENT_NAME = "experiment_name"
    SEED = "seed"

    RESULTS = "results"
    CHECKPOINT_PATH = "checkpoint_path"
    EXPERIMENT_TIMESTAMP = "experiment_timestamp"
    VISITATION_PENALTY = "visitation_penalty"
    INITIALISATION = "initialisation"
    RANDOM = "random"
    ZEROS = "zeros"
    ONES = "ones"
    TYPE = "type"
    SARSA = "sarsa"
    EXPECTED_SARSA = "expected_sarsa"
    Q_LEARNING = "q_learning"
